version: '3'

volumes:
    database_volume:

networks:
    backend:
    frontend:

services:
    database:
        container_name: evatool_database
        image: mysql:8.0.24
        command: --default-authentication-plugin=mysql_native_password
#        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - 3306:3306
#            - ${DB_PORT}:3306
        networks:
            - backend
        volumes:
            - database_volume:/var/lib/mysql

    backend:
        container_name: evatool_backend
        image: evatool/evatool-backend:latest
#        restart: always
#        environment:
#            DB_PORT: ${DB_PORT}
#            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - 443:8080
#            - ${BACKEND_PORT}:8080
        networks:
            - backend
            - frontend
        depends_on:
            - database

    frontend:
        container_name: evatool_frontend
        image: evatool/evatool-frontend:latest
#        restart: always
#        environment:
#            HOST_URL: ${HOST_URL}
#            BACKEND_PORT: ${BACKEND_PORT}
        ports:
            - 80:80
#            - ${FRONTEND_PORT}:80
        networks:
            - frontend
        depends_on:
            - backend

#    keycloak:
#        container_name: evatool_keycloak
#        image: ??
#        restart: always
#        environment:
#            - ???
#        networks:
#            - backend
#        depends_on:
#            - database
#             - backend
