name: Integration Testing (dev)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup auxillary systems
        run: |
          docker run --name evatool-test-db -p 3306:3306 -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=evatooldb -d mysql:8.0.24
          docker run --name evatool-test-auth -p 8081:8080 -v ${PWD}/src/main/resources/auth/keycloak:/opt/jboss/keycloak/imports -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -e KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/evatool-realm.json -d quay.io/keycloak/keycloak:13.0.0
          mvn flyway:baseline
          mvn flyway:migrate
          # init db with maven flyway plugin.
          # maybe wait a few seconds...

      - name: Integration Test
        run: mvn -B clean install -P integration --file ./pom.xml -Dgroups=integration
