name: Scan docker image (dev)

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'maven'

      - name: Build
        run: |
          mvn clean install -P prod -Dmaven.test.skip=true --file pom.xml

      - name: Build docker image
        run: docker build -t evatool/evatool-backend:local .

      - name: Scan docker image
        run: docker scan evatool/evatool-backend:local --accept-license --dependency-tree --file Dockerfile --exclude-base
