name: Unit Testing (dev)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: Zulu OpenJDK
          java-version: 11
          cache: 'maven'

      - name: Unit Test
        run: mvn -B clean install --file ./pom.xml -Dgroups=\!integration
