name: Deploy to DockerHub (main)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Unit Test
        run: |
          mvn test --file pom.xml -Dgroups=\!integration

      - name: Build
        run: |
          mvn clean install -P prod -Dmaven.test.skip=true --file pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: evatool/evatool-backend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Run docker-compose on remote server
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USER }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PORT: ${{ secrets.PORT }}
          SCRIPT: |
            cd evatool
            git pull https://github.com/EVATool/evatool
            cd docker
            docker-compose down
            docker image rm evatool/evatool-backend:latest
            docker-compose up -d
